@apiUrl = http://localhost:3000/api

#
GET {{apiUrl}}/usuarios
Content-Type: application/json
###

# Inserir novo cliente
POST {{apiUrl}}/usuarios
Content-Type: application/json

{
 "nome": "Fulano2", 
 "cpf": "99999999", 
 "telefone": "999999999", 
 "email": "Fulano2@teste.com", 
 "senha": "1234",
 "tipoUsuario": "1"
}
###

