@apiUrl = http://localhost:3000/api

# Obter a lista 
GET {{apiUrl}}/veterinarios
Content-Type: application/json
###

# Inserir novo 
POST {{apiUrl}}/veterinarios
Content-Type: application/json

{
   "nome":"Vitoria",
   "telefone":"99999999",
   "crmv":"999999999",
   "email":"vitoria@veterinario.com",
   "senha":"1234",
}
###

# Alterar 
PUT {{apiUrl}}/veterinarios
Content-Type: application/json

{
 "_id": "634d8e24e51e8f2bb3cf1fac",
    "nome": "João",
    "crmv": "12345678",
    "telefone": "(54) 9 9999-9999",
    "email": "joao@veterinario.com",
    "senha": "1234"
}
###

# Autenticação 
POST {{apiUrl}}/loginVeterinario
Content-Type: application/json

{
    "email": "joao@veterinario.com",
    "senha": "1234"
}
###
